for %%a in (
	arg_allowAsterisk
	arg_allowEqual
	arg_allowQuotationMark
	arg_allowSpace
	arg_allowTab
	asterisk
	charIsSafe
	checkChar
	checkCurrent
	checkExec
	checkObjectPath
	checkOperation
	checkString
	checkVar
	checkValue
	checkVariableName
	currentLine
	dispCurrent
	dontOverlap
	emptyLine
	end
	equal
	exec
	fileFound
	fontFilePath
	functionDeprecated
	functionExists
	gameNameValid
	getArgs
	getRandom
	getRandomRange
	halfWidth
	isCached
	isNumber
	initCurrent
	labelLength
	line
	lineContent
	lineLength
	new
	newArg
	newId6
	newPid
	newProperty_alignX
	newProperty_alignY
	newProperty_endXpos
	newProperty_endYpos
	newProperty_height
	newProperty_hovering
	newProperty_moveTo
	newProperty_onClick
	newProperty_sprite
	newProperty_textLabel
	newProperty_type
	newProperty_width
	newProperty_xpos
	newProperty_ypos
	newValue
	newXpos
	newYpos
	number
	offset1
	offset2
	offset3
	offset4
	parseProperty1
	parseProperty2
	parseProperty3
	parseProperty4
	parseProperty5
	parseProperty6
	parseProperty7
	parseProperty8
	parseProperty9
	parseProperty10
	performOperation
	quotationMark
	renderCurrent
	renderLine
	renderLines
	runtimeVersionMatches
	semiColon
	shitWorkaround
	space
	startArgument
	stringHasLetters
	stringHasNumbers
	stringHasSpaces
	stringHasSymbols
	stringHasUnwantedChars
	stringIsSafe
	stringLength
	tab
	textWidth
	timer_wait_t1
	timer_wait_t2
	timer_wait_tDiff
	trailingSpace
	unload
	useButtonProperties
	valid
	valueValid
	variableLength
	variableName
	variableNameEnd
	variableOffset
) do set %%a=
exit /b 0