for /l %%a in (1,1,56) do set b%%a=                                                                                        
set /a objectCount=0
set /a scriptCount=0
set /a maxLinesPerFrame=50
set /a addLinesPerFrame=10
set /a maxFps=25
set /a maxTps=25
set /a lineCharLimit=200
set halfRender=false
set /a debugTitlebar=0
set /a updateDiscordRpc=9999
set /a saveTimePlayed=9999
set /a updateTitle=9999
set scriptSafetyCacheFinished=false
set title=Initializing runtime...
set screenEffect=fadeToNormal
set screenEffectLength=normal
set /a screenColor=0
set /a skipDisp=5
set /a screenEffectStartingColor=0
set buttonsDisabled=false
set staticButtons=true
set staticText=true
set /a yssLinesExecuted=0
exit /b 0